### ISSUE TITLE
a issue about sim2real

### ISSUE THREAD

**Issue by happy-my** [UT-Austin-RPL/PRELUDE#1]
Hello,

Thanks a lot for providing this useful code. I'm working on a real robot A1 and I have no problem training the policy in the simulation. Do you have any plan to release the code on A1 hardware? It would be great if you publish it.

**Comment by kiwi-sherbet** [comment]
Thank you for your interest in my project. While the purpose of releasing our codebase is for benchmarking, our studies are regulated by UT IRB, so we are unable to share real-world data of human subjects. As a result, we currently do not have plans to release our script for the real robot. However, I can provide some guidance for implementing real robot experiments, and I hope this will be helpful for your implementation.

**Comment by kiwi-sherbet** [comment]
Thank you for your interest in my project!

Due to our studies being regulated by UT's [IRB](https://research.utexas.edu/ors/human-subjects/), we are unable to share real-world data of human subjects. As the goal of this codebase is to help benchmark `PRELUDE` with other methods, we have decided to release only the simulation scripts. However, I would be happy to provide some pointers for implementing real robot experiments. I hope these can be helpful.

- Sim-to-real of Gait Controller: our RL environments and HW scripts for Gait Controller is based on Google's `motion-imitation` [repo](https://github.com/erwincoumans/motion_imitation/tree/master/motion_imitation).
- Estimating demostrators' actions Data-collection for Navigation Controller: we used [this ROS package](https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy ) for Realsense T265 cameras.
- Realsense D435/D435i library for MacMini: we used this [repo](https://github.com/cansik/pyrealsense2-macosx).

**Comment by kiwi-sherbet** [comment]
Thank you for your interest in our project!

Due to our studies being regulated by UT's [IRB](https://research.utexas.edu/ors/human-subjects/), we are unable to share real-world data of human subjects. As the goal of this codebase is to help benchmark `PRELUDE` with other methods, we have decided to release only the simulation scripts. However, I would be happy to provide some pointers for implementing real robot experiments. I hope these can be helpful.

- Sim-to-real of Gait Controller: our RL environments and HW scripts for Gait Controller are based on Google's `motion-imitation` [repo](https://github.com/erwincoumans/motion_imitation/tree/master/motion_imitation).
- Estimating demostrators' actions Data-collection for Navigation Controller: we used [this ROS package](https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy ) for Realsense T265 cameras.
- Realsense D435/D435i library for MacMini: we used this [repo](https://github.com/cansik/pyrealsense2-macosx).

**Comment by happy-my** [comment]
Thanks a lot！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mingyo ***@***.***&gt;; 
发送时间: 2023年3月31日(星期五) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [UT-Austin-RPL/PRELUDE] a issue about sim2real (Issue #1)





 
Thank you for your interest in my project!
 
Due to our studies being regulated by UT's IRB, we are unable to share real-world data of human subjects. As the goal of this codebase is to help benchmark PRELUDE with other methods, we have decided to release only the simulation scripts. However, I would be happy to provide some pointers for implementing real robot experiments. I hope these can be helpful.
  
Sim-to-real of Gait Controller: our RL environments and HW scripts for Gait Controller is based on Google's motion-imitation repo.
 
Estimating demostrators' actions Data-collection for Navigation Controller: we used this ROS package for Realsense T265 cameras.
 
Realsense D435/D435i library for MacMini: we used this repo.
